/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dqwsohcduyrckuxlpknv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxd3NvaGNkdXlyY2t1eGxwa252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTk2MDAsImV4cCI6MjA3MDEzNTYwMH0._BSDQ-Pcxi1yNziR_U_7zMVzs1e-QvunztSv8EOVx8E"